// Data is served as a static JSON file generated by the GitHub Actions scraper

// Stat normalisation — maps raw wiki keys to display labels and formatters
const STAT_MAP = [
  {
    keys: ["max velocity", "maximum velocity", "top speed"],
    label: "Top Speed",
    format: v => {
      // Wiki gives either "kmh / mph" or "mph / kmh" — normalise to "N kph / N mph"
      const parts = v.split("/").map(s => s.trim());
      if (parts.length === 2) {
        const [a, b] = parts.map(p => parseFloat(p));
        // Determine which is kph (larger number)
        const kph = Math.max(a, b), mph = Math.min(a, b);
        return `${Math.round(kph)} kph / ${mph.toFixed(1)} mph`;
      }
      return v;
    }
  },
  {
    keys: ["drivetrain"],
    label: "Drivetrain",
    format: v => v.split("(")[0].trim()  // strip parenthetical notes
  },
  {
    keys: ["mass"],
    label: "Mass",
    format: v => {
      const parts = v.split("/").map(s => s.trim());
      if (parts.length === 2) {
        return `${parseFloat(parts[0]).toLocaleString()} kg / ${parseFloat(parts[1]).toLocaleString()} lbs`;
      }
      return v;
    }
  },
];

// ─── Price helpers ──────────────────────────────────────────────────────────

function parsePrice(priceStr) {
  if (!priceStr) return null;
  const cleaned = priceStr.replace(/[^0-9]/g, "");
  return cleaned ? parseInt(cleaned, 10) : null;
}

function formatPrice(num) {
  if (!num) return null;
  return "$" + num.toLocaleString("en-US");
}

function discountedPrice(price, pct) {
  return Math.round(price * (1 - pct / 100));
}

// ─── Card rendering ─────────────────────────────────────────────────────────

function buildPriceHTML(vehicle) {
  const raw = vehicle.price;
  const pct = vehicle.discount;
  const price = parsePrice(raw);

  if (!price) {
    return raw
      ? `<span class="price-normal">${raw}</span>`
      : `<span class="stat-value" style="color:var(--text-muted)">Price unknown</span>`;
  }

  if (pct) {
    const sale = discountedPrice(price, pct);
    return `
      <span class="price-original">${formatPrice(price)}</span>
      <span class="price-discounted">${formatPrice(sale)}</span>
    `;
  }
  return `<span class="price-normal">${formatPrice(price)}</span>`;
}

function buildStatsHTML(stats) {
  if (!stats || Object.keys(stats).length === 0) return "";
  const entries = [];
  for (const def of STAT_MAP) {
    // Find matching stat key (case-insensitive)
    for (const [k, v] of Object.entries(stats)) {
      if (def.keys.some(key => k.toLowerCase().includes(key))) {
        try {
          entries.push([def.label, def.format(v)]);
        } catch(e) {
          entries.push([def.label, v]);
        }
        break;
      }
    }
  }
  if (entries.length === 0) return "";
  return entries.map(([k, v]) => `
    <div class="stat-item">
      <span class="stat-label">${k}</span>
      <span class="stat-value">${v}</span>
    </div>
  `).join("");
}

function buildCard(vehicle) {
  const removed = vehicle.removed;
  const badges = [];
  if (vehicle.discount) {
    badges.push(`<span class="badge badge-discount">-${vehicle.discount}%</span>`);
  }
  if (removed) {
    badges.push(`<span class="badge badge-removed">Removed</span>`);
  }
  if (!removed && vehicle.previously_available && !vehicle.store) {
    badges.push(`<span class="badge badge-story">Story Mode</span>`);
  }

  const imgHTML = vehicle.image
    ? `<img src="${vehicle.image}" alt="${vehicle.name}" loading="lazy" onerror="this.parentElement.innerHTML='<div class=card-no-image><span>No image</span></div>'" />`
    : `<div class="card-no-image"><span>No image</span></div>`;

  const statsHTML = buildStatsHTML(vehicle.stats);
  const priceHTML = buildPriceHTML(vehicle);
  const storeLabel = vehicle.removed || vehicle.previously_available ? 'Previously at' : 'Available at';
  const storeHTML = vehicle.store
    ? `<span class="store-name ${vehicle.removed || vehicle.previously_available ? 'store-removed' : ''}">${storeLabel}: ${vehicle.store}</span>`
    : "";
  const wikiHTML = vehicle.wiki_url
    ? `<a href="${vehicle.wiki_url}" target="_blank" class="wiki-link">View on GTA Wiki ↗</a>`
    : "";

  return `
    <div class="vehicle-card${removed ? " removed" : ""}">
      <div class="card-image-wrap">
        ${imgHTML}
        <div class="badge-wrap">${badges.join("")}</div>
      </div>
      <div class="card-body">
        <p class="card-name">${vehicle.name}</p>
        <div class="card-price-row">${priceHTML}</div>
        ${storeHTML}
        ${statsHTML ? `<div class="card-stats">${statsHTML}</div>` : ""}
      </div>
      ${wikiHTML ? `<div class="card-footer">${wikiHTML}</div>` : ""}
    </div>
  `;
}

function renderGrid(gridEl, vehicles) {
  if (!vehicles || vehicles.length === 0) {
    gridEl.innerHTML = `<p style="color:var(--text-muted);font-family:var(--font-cond);letter-spacing:.1em;text-transform:uppercase;font-size:13px">No vehicles found.</p>`;
    return;
  }
  gridEl.innerHTML = vehicles.map(buildCard).join("");
}

function renderGroupedDiscounts(containerEl, groups) {
  if (!groups || groups.length === 0) {
    containerEl.innerHTML = `<p style="color:var(--text-muted);font-family:var(--font-cond);letter-spacing:.1em;text-transform:uppercase;font-size:13px">No vehicles found.</p>`;
    return;
  }
  groups = groups.filter(g => !g.group.toLowerCase().includes('gun van'));
  // Filter removed vehicles from discounts — discount is irrelevant if not in GTA Online
  groups = groups.map(g => ({...g, vehicles: g.vehicles.filter(v => !v.removed && !v.previously_available)}));
  groups.sort((a, b) => b.group.toLowerCase().includes('law enforcement') ? 1 : -1);
  containerEl.innerHTML = groups.map(group => `
    <div class="discount-group">
      <h3 class="group-title">${group.group}</h3>
      <div class="vehicle-grid">${group.vehicles.map(buildCard).join("")}</div>
    </div>
  `).join("");
}

// ─── Navigation ─────────────────────────────────────────────────────────────

const sections = {
  discounts: document.getElementById("section-discounts"),
  luxury:    document.getElementById("section-luxury"),
  pdm:       document.getElementById("section-pdm"),
};

function showSection(name) {
  Object.entries(sections).forEach(([key, el]) => {
    el.classList.toggle("hidden", key !== name);
  });
  document.querySelectorAll(".nav-btn").forEach(btn => {
    btn.classList.toggle("active", btn.dataset.section === name);
  });
}

document.querySelectorAll(".nav-btn").forEach(btn => {
  btn.addEventListener("click", () => showSection(btn.dataset.section));
});

// ─── Data loading ────────────────────────────────────────────────────────────

async function loadDeals() {
  document.getElementById("loading").classList.remove("hidden");
  document.getElementById("error-screen").classList.add("hidden");
  Object.values(sections).forEach(s => s.classList.add("hidden"));

  try {
    const res = await fetch("data.json?t=" + Date.now());
    if (!res.ok) throw new Error(`HTTP ${res.status}`);
    const data = await res.json();
    if (data.error) throw new Error(data.error);

    // Update header
    document.getElementById("date-range").textContent = data.date_range || "";
    const postLink = document.getElementById("post-link");
    if (data.post_url) {
      postLink.href = data.post_url;
      postLink.style.display = "";
    } else {
      postLink.style.display = "none";
    }

    // Render grids
    renderGroupedDiscounts(document.getElementById("grid-discounts"), data.discount_groups || [{group: "Discounts", vehicles: data.discounts}]);
    renderGrid(document.getElementById("grid-luxury"),    data.luxury_autos);
    renderGrid(document.getElementById("grid-pdm"),       data.pdm);

    document.getElementById("loading").classList.add("hidden");
    showSection("discounts");

  } catch (err) {
    document.getElementById("loading").classList.add("hidden");
    document.getElementById("error-screen").classList.remove("hidden");
    document.getElementById("error-msg").textContent = `Error: ${err.message}`;
    console.error(err);
  }
}

document.getElementById("refresh-btn").addEventListener("click", () => {
  loadDeals();
});

loadDeals();
