// Data is served as a static JSON file generated by the GitHub Actions scraper


// ─── Price helpers ──────────────────────────────────────────────────────────

function parsePrice(priceStr) {
  if (!priceStr) return null;
  const cleaned = priceStr.replace(/[^0-9]/g, "");
  return cleaned ? parseInt(cleaned, 10) : null;
}

function formatPrice(num) {
  if (!num) return null;
  return "$" + num.toLocaleString("en-US");
}

function discountedPrice(price, pct) {
  return Math.round(price * (1 - pct / 100));
}

// ─── Card rendering ─────────────────────────────────────────────────────────

function buildPriceHTML(vehicle) {
  const raw = vehicle.price;
  const pct = vehicle.discount;
  const price = parsePrice(raw);

  if (!price) {
    return raw
      ? `<span class="price-normal">${raw}</span>`
      : `<span class="stat-value" style="color:var(--text-muted)">Price unknown</span>`;
  }

  if (pct) {
    const sale = discountedPrice(price, pct);
    return `
      <span class="price-original">${formatPrice(price)}</span>
      <span class="price-discounted">${formatPrice(sale)}</span>
    `;
  }
  return `<span class="price-normal">${formatPrice(price)}</span>`;
}

function buildStatsHTML(vehicle) {
  const b = vehicle.broughy || {};
  if (Object.keys(b).length === 0) return "";
  const entries = [];
  if (b.top_speed_mph) {
    const kph = b.top_speed_kph || Math.round(b.top_speed_mph * 1.60934);
    const rank = b.top_speed_rank_class ? `#${b.top_speed_rank_class} in ${b.vehicle_class || ''}` : '';
    entries.push(['Top Speed', `${kph} kph / ${b.top_speed_mph} mph`, rank]);
  }
  if (b.lap_time) {
    const rank = b.lap_time_rank_class ? `#${b.lap_time_rank_class} in ${b.vehicle_class || ''}` : '';
    entries.push(['Lap Time', b.lap_time, rank]);
  }
  if (b.drivetrain) entries.push(['Drivetrain', b.drivetrain, '']);
  if (b.seats) entries.push(['Seats', b.seats, '']);
  if (entries.length === 0) return "";
  return entries.map(([label, value, sub]) => `
    <div class="stat-item">
      <span class="stat-label">${label}</span>
      <span class="stat-value">${value}</span>
      ${sub ? `<span class="stat-rank">${sub}</span>` : ''}
    </div>
  `).join('');
}

function buildCard(vehicle) {
  const removed = vehicle.removed;
  const badges = [];
  if (vehicle.discount) {
    badges.push(`<span class="badge badge-discount">-${vehicle.discount}%</span>`);
  }
  if (removed) {
    badges.push(`<span class="badge badge-removed">Removed</span>`);
  }
  if (!removed && vehicle.previously_available && !vehicle.store) {
    badges.push(`<span class="badge badge-story">Story Mode</span>`);
  }

  const imgHTML = vehicle.image
    ? `<img src="${vehicle.image}" alt="${vehicle.name}" loading="lazy" onerror="this.parentElement.innerHTML='<div class=card-no-image><span>No image</span></div>'" />`
    : `<div class="card-no-image"><span>No image</span></div>`;

  const statsHTML = buildStatsHTML(vehicle);
  const priceHTML = buildPriceHTML(vehicle);
  // Determine store label and style
  let storeLabel, storeClass;
  if (vehicle.removed || vehicle.previously_available) {
    const inLuxury = (window._luxuryVehicles || []).some(v => v.name.toLowerCase() === vehicle.name.toLowerCase());
    const inPDM = (window._pdmVehicles || []).some(v => v.name.toLowerCase() === vehicle.name.toLowerCase());
    if (inLuxury || inPDM) {
      storeLabel = 'Only available at';
      storeClass = 'store-showroom-only';
      // Override store with the actual showroom name
      vehicle = {...vehicle, store: inLuxury ? 'Luxury Autos' : 'Premium Deluxe Motorsport'};
    } else {
      storeLabel = 'Previously at';
      storeClass = 'store-removed';
    }
  } else {
    storeLabel = 'Available at';
    storeClass = '';
  }
  const storeHTML = vehicle.store
    ? `<span class="store-name ${storeClass}">${storeLabel}: ${vehicle.store}</span>`
    : "";
  const wishlisted = isWishlisted(vehicle.name);
  const wishlistBtn = vehicle.discount
    ? `<button class="wishlist-btn ${wishlisted ? 'wishlisted' : ''}" data-name="${vehicle.name}" title="${wishlisted ? 'Remove from wishlist' : 'Add to wishlist'}">${wishlisted ? '♥' : '♡'}</button>`
    : "";
  const wikiHTML = vehicle.wiki_url
    ? `<a href="${vehicle.wiki_url}" target="_blank" class="wiki-link">View on GTA Wiki ↗</a>`
    : "";

  return `
    <div class="vehicle-card${removed ? " removed" : ""}">
      <div class="card-image-wrap">
        ${imgHTML}
        <div class="badge-wrap">${badges.join("")}</div>
      </div>
      <div class="card-body">
        <p class="card-name">${vehicle.name}</p>
        <div class="card-price-row">${priceHTML}</div>
        ${storeHTML}
        ${statsHTML ? `<div class="card-stats">${statsHTML}</div>` : ""}
      </div>
      <div class="card-footer">
        ${wikiHTML}
        ${wishlistBtn}
      </div>
    </div>
  `;
}

function renderGrid(gridEl, vehicles) {
  if (!vehicles || vehicles.length === 0) {
    gridEl.innerHTML = `<p style="color:var(--text-muted);font-family:var(--font-cond);letter-spacing:.1em;text-transform:uppercase;font-size:13px">No vehicles found.</p>`;
    return;
  }
  gridEl.innerHTML = vehicles.map(buildCard).join("");
}

function renderGroupedDiscounts(containerEl, groups) {
  if (!groups || groups.length === 0) {
    containerEl.innerHTML = `<p style="color:var(--text-muted);font-family:var(--font-cond);letter-spacing:.1em;text-transform:uppercase;font-size:13px">No vehicles found.</p>`;
    return;
  }
  groups = groups.filter(g => !g.group.toLowerCase().includes('gun van'));
  // For removed vehicles: only show in discounts if they appear in a showroom this week
  // Build showroom set directly from data passed in (not globals which may not be set yet)
  groups = groups.map(g => ({...g, vehicles: g.vehicles.filter(v => {
    if (!v.removed && !v.previously_available) return true;
    const inShowroom = (window._luxuryVehicles || []).concat(window._pdmVehicles || [])
      .some(sv => sv.name.toLowerCase() === v.name.toLowerCase());
    return inShowroom;
  })}));
  groups.sort((a, b) => b.group.toLowerCase().includes('law enforcement') ? 1 : -1);
  const showHeaders = groups.length > 1;
  containerEl.innerHTML = groups.map(group => `
    <div class="discount-group">
      ${showHeaders ? `<h3 class="group-title">${group.group}</h3>` : ''}
      <div class="vehicle-grid">${group.vehicles.map(buildCard).join("")}</div>
    </div>
  `).join("");
}

// ─── Navigation ─────────────────────────────────────────────────────────────

const sections = {
  wishlist:  document.getElementById("section-wishlist"),
  discounts: document.getElementById("section-discounts"),
  luxury:    document.getElementById("section-luxury"),
  pdm:       document.getElementById("section-pdm"),
};

// ─── Wishlist ────────────────────────────────────────────────────────────────

const WISHLIST_KEY = "gta_wishlist";

function loadWishlist() {
  try {
    return JSON.parse(localStorage.getItem(WISHLIST_KEY)) || { dateRange: "", items: [] };
  } catch { return { dateRange: "", items: [] }; }
}

function saveWishlist(wl) {
  localStorage.setItem(WISHLIST_KEY, JSON.stringify(wl));
}

function syncWishlist(currentDateRange, allDiscountedNames) {
  let wl = loadWishlist();
  if (wl.dateRange !== currentDateRange) {
    // New week — remove items no longer discounted, keep ones that rolled over
    wl.items = wl.items.filter(name => allDiscountedNames.has(name.toLowerCase()));
    wl.dateRange = currentDateRange;
    saveWishlist(wl);
  }
  return wl;
}

function toggleWishlist(name, currentDateRange) {
  let wl = loadWishlist();
  wl.dateRange = currentDateRange;
  const idx = wl.items.findIndex(n => n.toLowerCase() === name.toLowerCase());
  if (idx === -1) {
    wl.items.push(name);
  } else {
    wl.items.splice(idx, 1);
  }
  saveWishlist(wl);
  return wl;
}

function isWishlisted(name) {
  const wl = loadWishlist();
  return wl.items.some(n => n.toLowerCase() === name.toLowerCase());
}

function updateWishlistCount() {
  const count = loadWishlist().items.length;
  const el = document.getElementById("wishlist-count");
  if (el) el.textContent = count > 0 ? count : "";
}

function showSection(name) {
  Object.entries(sections).forEach(([key, el]) => {
    el.classList.toggle("hidden", key !== name);
  });
  document.querySelectorAll(".nav-btn").forEach(btn => {
    btn.classList.toggle("active", btn.dataset.section === name);
  });
}

document.querySelectorAll(".nav-btn").forEach(btn => {
  btn.addEventListener("click", () => showSection(btn.dataset.section));
});

// ─── Data loading ────────────────────────────────────────────────────────────

async function loadDeals() {
  document.getElementById("loading").classList.remove("hidden");
  document.getElementById("error-screen").classList.add("hidden");
  Object.values(sections).forEach(s => s.classList.add("hidden"));

  try {
    const res = await fetch("data.json?t=" + Date.now());
    if (!res.ok) throw new Error(`HTTP ${res.status}`);
    const data = await res.json();
    if (data.error) throw new Error(data.error);

    // Update header
    document.getElementById("date-range").textContent = data.date_range || "";
    const postLink = document.getElementById("post-link");
    if (data.post_url) {
      postLink.href = data.post_url;
      postLink.style.display = "";
    } else {
      postLink.style.display = "none";
    }

    // Render grids
    // Store showroom vehicles globally BEFORE rendering discounts so filter works
    window._luxuryVehicles = data.luxury_autos || [];
    window._pdmVehicles = data.pdm || [];
    window._dateRange = data.date_range || "";

    // Sync wishlist with current week
    const allDiscountedNames = new Set(
      (data.discounts || []).map(v => v.name.toLowerCase())
    );
    syncWishlist(data.date_range || "", allDiscountedNames);
    updateWishlistCount();

    window._allDiscounts = data.discounts || [];
    renderGroupedDiscounts(document.getElementById("grid-discounts"), data.discount_groups || [{group: "Discounts", vehicles: data.discounts}]);
    renderGrid(document.getElementById("grid-luxury"),    data.luxury_autos);
    renderGrid(document.getElementById("grid-pdm"),       data.pdm);
    renderWishlist(data.discounts || []);

    document.getElementById("loading").classList.add("hidden");
    showSection("discounts");

  } catch (err) {
    document.getElementById("loading").classList.add("hidden");
    document.getElementById("error-screen").classList.remove("hidden");
    document.getElementById("error-msg").textContent = `Error: ${err.message}`;
    console.error(err);
  }
}

function renderWishlist(allDiscounts) {
  const wl = loadWishlist();
  const grid = document.getElementById("grid-wishlist");
  const empty = document.getElementById("wishlist-empty");
  if (wl.items.length === 0) {
    grid.innerHTML = "";
    empty.classList.remove("hidden");
    return;
  }
  empty.classList.add("hidden");
  const wishlisted = allDiscounts.filter(v =>
    wl.items.some(n => n.toLowerCase() === v.name.toLowerCase())
  );
  grid.innerHTML = wishlisted.map(buildCard).join("");
}

// Single delegated click handler — set up once, works for all cards
document.addEventListener("click", e => {
  const btn = e.target.closest(".wishlist-btn");
  if (!btn) return;
  e.stopPropagation();
  const name = btn.dataset.name;
  toggleWishlist(name, window._dateRange || "");
  updateWishlistCount();
  // Update all hearts for this vehicle without re-rendering
  document.querySelectorAll(`.wishlist-btn[data-name="${CSS.escape(name)}"]`).forEach(b => {
    const wl = isWishlisted(name);
    b.textContent = wl ? "\u2665" : "\u2661";
    b.classList.toggle("wishlisted", wl);
    b.title = wl ? "Remove from wishlist" : "Add to wishlist";
  });
  // Re-render wishlist tab contents
  renderWishlist(window._allDiscounts || []);
});

function attachWishlistHandlers() {} // no-op, kept for compatibility

document.getElementById("refresh-btn").addEventListener("click", () => {
  loadDeals();
});

loadDeals();